### ISSUE TITLE
QRLJacker Sessions captured automatically, none of them loads

### ISSUE THREAD

**Issue by ashu223** [OWASP/QRLJacking#128]
QRLJacker sessions captured automatically even without scanning. None of them loads.
only 1 session captured from scanning but it does not load. When i enter the code "sessions -i 4" it goes to Whatsapp web page loads and remains in the Whatsapp QR code page.
![Wa](https://user-images.githubusercontent.com/55798020/99898253-08ef9d80-2cc6-11eb-9795-1d90c8471f2b.png)

**Comment by melbadry9** [comment]
I can't reproduce this issue. Can you please specify the python version used and enable debug mode?

**Comment by ashu223** [comment]
> 
> 
> I can't reproduce this issue. Can you please specify the python version used and enable debug mode?

Python 3.7.5

All are working fine. after run command, i get this issue. Im not sure about the debug mode.

**Comment by ashu223** [comment]
> 
> 
> I can't reproduce this issue. Can you please specify the python version used and enable debug mode?

I checked with "debug" command. It shows degub mode enabled

**Comment by melbadry9** [comment]
I was able to reproduce this issue. This looks like Python 3.8.* issue, We will investigate further.

**Comment by ashu223** [comment]
any update on this issue?

**Comment by melbadry9** [comment]
We still working on a fix.

**Comment by Mohammed-Ashour** [comment]
The same issue happened with `Python 3.7.9` it keeps saying
`
[+] Got session on whatsapp module 

[+] Session saved successfully
`
and when I use any session of them, it just opens WhatsApp, loading, then go back to the home page without signing in
but when you check the Whatsapp app on the phone it captures that you already signed in on WhatsApp web.

**Comment by never-sur** [comment]
the same problem. a month has passed, do you have news?

**Comment by melbadry9** [comment]
Using `python 3` before `python 3.7.9` should be working fine. We have a webdriver  issue with session storage and we're working on getting it fixed as soon as possible.

**Comment by never-sur** [comment]
installed python version 3.7.9. Still not working.
I can't find version 3.7.6 and younger

**Comment by melbadry9** [comment]
You can download it from official website [Python Releases](https://www.python.org/downloads/).

**Comment by never-sur** [comment]
yes, but the library only works with version 3.7 and higher

**Comment by Mohammed-Ashour** [comment]
I used Pyenv to test the module on Python 3.7.1 but still having the same issue, the session can't load, and web whatsapp opens on the home page without signing in (it gives you the loading page twice then redirects you to the home page)

**Comment by never-sur** [comment]
Mohammed-Ashour, 
I have the same situation

**Comment by djrose305** [comment]
glad i am not alone on this issue

**Comment by SymbianSyMoh** [comment]
@melbadry9 What is the status of this issue?

**Comment by SymbianSyMoh** [comment]
Hello Maintainers, Can you take a look at this issue?

@melbadry9
@samm0uda
@Lekssays
@0xGuindi
@Kiro24
@MohamedAbdultawab
@mohmyo
@OmarMerghany
@TheRubick
@mikeashi
@mxfoxawy

**Comment by melbadry9** [comment]
Hi @SymbianSyMoh,

After digging into this issue turned out it not a web driver issue. WhatsApp web previously depended on cookies and local storage to maintain and establish web socket connection. Currently it depends on IndexedDB which QrlJacker has no support for yet.

Can someone please confirm this? 
@samm0uda @Lekssays @0xGuindi @Kiro24 @MohamedAbdultawab @mohmyo @OmarMerghany @TheRubick @mikeashi @mxfoxawy

**Comment by Lekssays** [comment]
I confirm this explanation. It's not a web driver issue.

**Comment by never-sur** [comment]
hello1. Will the project be supported further?
2. Is it realistic to solve this problem at all?

**Comment by never-sur** [comment]
hello again, if it's not a web driver issue - please answer the question:
1. Will the project be supported further?
2. Is it realistic to solve this problem at all?

**Comment by melbadry9** [comment]
Hi @never-sur, 

Rest assured that the project will be supported and the issue will be fixed but please give us the time to solve it and we will update the OWASP community once the project is fully patched. 

Thanks for your support and understanding.

**Comment by ashwin752** [comment]
I'm too experiencing the same issue which have mentioned above.. Any updates??

**Comment by never-sur** [comment]
@ashwin752 I think that there are no changes yet, otherwise the developers would have written about it. I'm also waiting for it to be fixed

**Comment by melbadry9** [comment]
I just committed 102173fb2b1e6f6b0fb9cd9a5a39c0c8af271089 a beta fix for this issue. Once the session has been captured you'll have to execute `run` command again, This will be fixed in final release.

**Comment by Yega23741234** [comment]
![51E3EDE2-A53F-4CB1-AB63-C3E65F245D16](https://user-images.githubusercontent.com/50628805/116140498-fca2bd00-a709-11eb-9303-622b77e5f906.jpeg)
I had this problem...
Any sollution?

**Comment by pwdbyqatux** [comment]
You need to use python 3.7 in a virtual environment i just did it from a fresh parrot os install couple days ago

**Comment by pwdbyqatux** [comment]
Also make sure u have port forwarding enabled if using over wan. https://youtu.be/TTf2MSPGuuA

**Comment by Yega23741234** [comment]
Its working perfectly but when i quit terminal and open it i cant open session

**Comment by Enigma1309** [comment]
Is This Thread DEAD
Please Fix this Issue 
 i am unable to use the captured session
please help


@melbadry9
@samm0uda
@Lekssays
@0xGuindi
@Kiro24
@MohamedAbdultawab
@mohmyo
@OmarMerghany
@TheRubick
@mikeashi
@mxfoxawy

**Comment by S-242** [comment]
I'm having the same issue as above. Is there any update on how to fix this? Thanks.

**Comment by pwdbyqatux** [comment]
> I'm having the same issue as above. Is there any update on how to fix this? Thanks.

Hi,I use python3.7-dev , and create a local environment in the qrljack folder. I found 3.7-dev to be the best version , also I use port 1337 and changed the ownership of the .x authority file to  my user instead of root user which allows Firefox to open Properly I think . Sometimes if you scan the code twice or just click enter a few times on the qrljack terminal  it ends up working out but sometimes it captures the session but doesn’t always show it.  Even with the syntax error showing , I can still get the session 
![00E05B0B-6B28-4DE1-8295-AB3CAF3BD963](https://user-images.githubusercontent.com/60446251/172027570-df3d55e3-a28c-4d4b-a977-41c07d435a9c.jpeg)

**Comment by khadeerbasha12** [comment]
it is not recognising run as an internal command

QrlJacker Module(grabber/whatsapp) > run                                                                                                                                    [!] run is not recognized as an internal command !                                                                                                                          [+] Maybe you meant : , runreload, refresh, resource                                                                                                                        [+] Type help or ? to learn more..

**Comment by pwdbyqatux** [comment]
> it is not recognising run as an internal command
> 
> QrlJacker Module(grabber/whatsapp) > run [!] run is not recognized as an internal command ! [+] Maybe you meant : , runreload, refresh, resource [+] Type help or ? to learn more..

means you dont have firefox properly installed,

**Comment by kaliyashu** [comment]
QrlJacker Module(grabber/whatsapp) > run
[+] Using the default useragent
[+] Running a thread to keep the QR image  [whatsapp]
Exception in thread QR updater thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kali/QRLJacking/QRLJacker/core/browser.py", line 133, in website_qr
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'
[+] Waiting for sessions on whatsapp
[+] Running a thread to detect Idle once it happens then click the QR reload button [whatsapp]
Exception in thread Idle detector thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
[+] Initializing webserver... [whatsapp]
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kali/QRLJacking/QRLJacker/core/browser.py", line 149, in check_img
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'

QrlJacker Module(grabber/whatsapp) > Exception in thread Webserver manager thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kali/QRLJacking/QRLJacker/core/browser.py", line 167, in serve_module
    self.browsers[module_name]["host"] = "http://"+host
KeyError: 'whatsapp'

**Comment by root-cyborg127** [comment]
I cant capture sessions at all the job is been created after scaning i am not able to fetch the session

**Comment by Mwdwk** [comment]
plz anyone reply the problem the sessions are not being captured any more
